package com.topblog.entity;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserId
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserName
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserNo
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    private Integer userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Sex
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    private Boolean sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserId
     *
     * @return the value of userinfo.UserId
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserId
     *
     * @param userid the value for userinfo.UserId
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserName
     *
     * @return the value of userinfo.UserName
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserName
     *
     * @param username the value for userinfo.UserName
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserNo
     *
     * @return the value of userinfo.UserNo
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public Integer getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserNo
     *
     * @param userno the value for userinfo.UserNo
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public void setUserno(Integer userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Sex
     *
     * @return the value of userinfo.Sex
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Sex
     *
     * @param sex the value for userinfo.Sex
     *
     * @mbggenerated Fri Mar 13 09:16:34 CST 2015
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }
}